CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    name VARCHAR(16) UNIQUE NOT NULL,
    email VARCHAR UNIQUE NOT NULL,
    pass VARCHAR NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
)
