version: "3.8"
services:
  idlemon:
    build:
      context: .
    ports:
      - "${PORT}:${PORT}"
    environment:
      - ENV=production
      - PORT=${PORT}
      - DB_HOST=postgres
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - REDIS_HOST=redis
    restart: on-failure
    depends_on:
      - redis
      - postgres
  redis:
    image: redis:6.0-alpine3.12
    ports:
      - "6379:6379"
  postgres:
    image: postgres:13.1-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      