version: "3.8"
services:
  server:
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      - ENV=development
      - DB_USER=postgres
      - DB_PASS=password
      - DB_HOST=postgres
      - REDIS_HOST=redis
    restart: always
    depends_on:
      - redis
      - postgres
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    restart: always
