version: "3.8"
services:
  server:
    build:
      context: .
    ports:
      - "3010:3010"
    restart: always
    environment:
      - ENV=${ENV}
      - DB_HOST=postgres
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - REDIS_HOST=redis
    depends_on:
      - redis
      - postgres
  redis:
    image: redis:6.0-alpine3.12
    ports:
      - "6379:6379"
    restart: always
  postgres:
    image: postgres:13.1-alpine
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
